# Generated by Django 3.0.6 on 2020-07-30 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import werkstatt.models
import werkstatt.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.PositiveSmallIntegerField(choices=[(1, 'de'), (2, 'en')], default=1)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('tuedo_number', models.CharField(blank=True, max_length=10, null=True)),
                ('meta', models.TextField(blank=True, null=True)),
                ('keywords', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('content',models.TextField(verbose_name='Content')),
                ('references', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('image_alt', models.CharField(max_length=100, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('featured_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('draft', models.BooleanField(default=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='werkstatt.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', werkstatt.models.CaseInsensitiveCharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('notice', models.TextField()),
                ('confirmed', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_email', models.EmailField(error_messages={'invalid': 'Ungültige E-Mail-Adresse.', 'unique': 'Diese E-Mail existiert bereits.'}, max_length=254, unique=True)),
                ('subscribe_hash', models.CharField(default=werkstatt.utils.getHashString, max_length=20)),
                ('unsubscribe_hash', models.CharField(default=werkstatt.utils.getHashString, max_length=20)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('comment_body', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=False)),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='werkstatt.BlogPost')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='werkstatt.Comment')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='categories',
            field=models.ManyToManyField(to='werkstatt.Category'),
        ),
    ]
