# Generated by Django 3.0.6 on 2020-08-19 15:09

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('werkstatt', '0002_auto_20200731_1918'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogpost',
            managers=[
                ('number', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_email',
            field=models.EmailField(error_messages={'invalid': 'Ungültige E-Mail-Adresse.', 'unique': 'Diese E-Mail ist bereits registriert.'}, max_length=254, unique=True),
        ),
    ]
