# Generated by Django 3.0.6 on 2020-08-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('werkstatt', '0003_auto_20200819_1709'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogpost',
            managers=[
            ],
        ),
    ]
