# Generated by Django 3.0.6 on 2020-08-31 09:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('werkstatt', '0006_auto_20200831_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
