# Generated by Django 3.0.6 on 2020-08-31 10:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('werkstatt', '0007_blogpost_content2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content2',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
