# Generated by Django 3.1.1 on 2020-09-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werkstatt', '0008_auto_20200831_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='meta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
