# Generated by Django 3.1.1 on 2020-09-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('werkstatt', '0011_milestones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Milestones',
            new_name='Milestone',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
