# Generated by Django 3.1.1 on 2020-09-15 12:49

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('werkstatt', '0012_auto_20200914_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitecontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'about')], null=True)),
                ('header', models.CharField(blank=True, max_length=100, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('draft', models.BooleanField(default=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'sitecontent',
                'ordering': ('position', 'header'),
            },
        ),
        migrations.DeleteModel(
            name='Milestone',
        ),
    ]
