# Generated by Django 3.1.1 on 2020-09-15 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('werkstatt', '0014_auto_20200915_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitecontent',
            options={'ordering': ('-position', 'header'), 'verbose_name_plural': 'sitecontent'},
        ),
    ]
