# Generated by Django 3.1.1 on 2020-10-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werkstatt', '0015_auto_20200915_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='site',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'about'), (1, 'datenschutz'), (2, 'references'), (3, 'imprint')], null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_email',
            field=models.EmailField(error_messages={'invalid': 'Bitte gültige E-Mail-Adresse eingeben.', 'unique': 'Diese E-Mail ist bereits registriert.'}, max_length=254, unique=True),
        ),
    ]
