# Generated by Django 3.1.1 on 2020-10-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werkstatt', '0016_auto_20201027_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, error_messages={'invalid': 'your custom error message'}, max_length=254, null=True),
        ),
    ]
