# Generated by Django 3.1.1 on 2020-10-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werkstatt', '0020_auto_20201028_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_email',
            field=models.EmailField(error_messages={'invalid': 'INVALID E-MAIL', 'required': 'REQUIRED'}, max_length=254, unique=True),
        ),
    ]
