# Generated by Django 3.1.1 on 2020-10-28 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werkstatt', '0021_auto_20201028_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='INVALID EMAIL')]),
        ),
    ]
