# Generated by Django 3.1.1 on 2020-10-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werkstatt', '0022_auto_20201028_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_email',
            field=models.EmailField(error_messages={'invalid': 'Bitte geben Sie eine gültige E-Mail-Adresse ein.', 'unique': 'Diese E-Mail ist bereits registriert.'}, max_length=254, unique=True),
        ),
    ]
