# Generated by Django 3.1.1 on 2020-11-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werkstatt', '0023_auto_20201028_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='meta',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
