# Generated by Django 3.1.1 on 2020-11-10 13:33

from django.db import migrations, models
import werkstatt.utils


class Migration(migrations.Migration):

    dependencies = [
        ('werkstatt', '0024_auto_20201108_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='confirm_hash',
            field=models.CharField(default=werkstatt.utils.getHashString, max_length=20),
        ),
    ]
