# Generated by Django 3.1.1 on 2020-11-15 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('werkstatt', '0025_comment_confirm_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='mf@123.de', max_length=320),
            preserve_default=False,
        ),
    ]
