# Generated by Django 3.1.1 on 2021-02-03 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('werkstatt', '0026_auto_20201115_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-date_posted']},
        ),
    ]
